name: Astronomer CI - Delete Preview Deployment

on:
  delete:
    branches:
      - "**"
env:
  ## Set your API token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Delete preview Deployment
      uses: astronomer/deploy-action@v0.12.0
      with:
        action: delete-deployment-preview
        deployment-id: cmn5wicbg0z2t01kyiw3bqatp
