name: Astronomer CI - Deploy code to preview

on:
  pull_request:
    branches:
      - main

env:
  ## Set your API token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.13
      continue-on-error: true  # Create action fails if deploy preview already exist, which is expected for subsequent commits in the PR
      with:
        action: create-deployment-preview
        deployment-id: cmn5wicbg0z2t01kyiw3bqatp
        workspace: ${{ secrets.ASTRO_WORKSPACE_ID }}
        wait-time: 10m # Max wait time for the preview deployment to be completed by the deploy action. The workflow will fail if the deployment fails to create within give time period.
    - name: Deploy code to preview
      uses: astronomer/deploy-action@v0.13
      with:
        action: deploy-deployment-preview
        deployment-id: cmn5wicbg0z2t01kyiw3bqatp
        workspace: ${{ secrets.ASTRO_WORKSPACE_ID }}
